# Generated by Django 4.2 on 2023-04-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
