# Generated by Django 4.2 on 2023-04-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_alter_videos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='detail',
            field=models.TextField(),
        ),
    ]
