# Generated by Django 4.2 on 2023-04-25 15:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_alter_about_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
