# Generated by Django 4.1.4 on 2023-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0004_alter_about_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(default='https://images.unsplash.com/photo-1611162616475-46b635cb6868?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80', upload_to='image'),
        ),
    ]
