# Generated by Django 4.1.4 on 2023-06-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0007_alter_videos_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
