# Generated by Django 4.1.4 on 2023-06-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0008_alter_videos_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_link',
            field=models.CharField(max_length=500),
        ),
    ]
